version: "3.11"

services:
   redis:
      image: redis:7-alpine
      restart: always
      env_file: .env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:/redis_data

   postgres:
      image: postgres:16-alpine
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   db_migrations:
      build: .
      restart: on-failure
      depends_on:
         - postgres
      env_file: .env
      command: sh -c "python -m alembic upgrade head"

   bot:
      build: .
      restart: always
      env_file: .env
      depends_on:
         - redis
         - postgres
         - db_migrations

volumes:
   redis-data:
   postgres-data:
